openapi: 3.0.0
info:
  title: "Projom.se Pokemon API documentation"
  version: 0.0.1

servers:
 - url: http://api.projom.se
   description: Projom API server

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

tags:
  - name: "Users"
    description: "All things user"
  - name: "Pokemons"
    description: "Query for your favorite pokemons!"
  - name: "Common"
    description: "Small and interesting, common, endpoints"
  - name: "Items"
    description: "Query for items"
  - name: "Recipes"
    description: "Query for item recipes"
paths:
  /users/login:
    $ref: "user.yml#/user"

  /pokemons:
    $ref: "pokemon.yml#/pokemon_list"
  /pokemons/checksum:
    $ref: "pokemon.yml#/pokemon_list_checksum"

  /fuel:
    $ref: "fuel.yml#/cost"
  /dice:
    $ref: "dice.yml#/roll"

  /items:
    $ref: "item.yml#/items"
  /items/random:
    $ref: "item.yml#/random_items"
  /items/{item_id}:
    $ref: "item.yml#/items_by_id"

  /items/recipes:
    $ref: "item/recipe.yml#/recipes"
  /items/recipes/random:
    $ref: "item/recipe.yml#/random_recipes"
  /items/recipes/{recipe_id}:
    $ref: "item/recipe.yml#/recipes_by_id"
